import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import SideNav from "@/components/sidenav"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200 text-gray-800`}>
        <div className="grid min-h-screen grid-cols-[auto,1fr] gap-4">
          <SideNav />
          <div>
            <div className="mx-auto mt-8 max-w-3xl">{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
